name: Check Latest Version Workflow

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '0 0 * * *'

jobs:
  check-version-and-create-issue:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Run the version check script
      id: version_check
      run: python .github/workflows/compare_latest_version.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Open GitHub Issue if new version is available
      if: steps.version_check.outputs.new_version_available == 'true'
      uses: JasonEtco/create-an-issue@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        title: "New snaphu version ${{ steps.version_check.outputs.remote_version }} available"
        body: |
          There is a new snaphu version available: ${{ steps.version_check.outputs.remote_version }}.
          Please update the codebase.
